# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('url', models.URLField(unique=True)),
                ('help_text', models.CharField(blank=True, help_text='资源类型为文档时，本字段为文档封面的URL地址', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('level', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=30, verbose_name='Difficulty Level')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '代码类型',
                'verbose_name_plural': '代码类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='topics')),
                ('official_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '主题/题材',
                'verbose_name_plural': '主题/题材',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.ResourceType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(to='resource.Topic'),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
