# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=1000, verbose_name='七嘴八舌')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='brief', verbose_name='配图')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简语',
                'verbose_name_plural': '简语',
                'db_table': 'albums_brief',
            },
        ),
    ]
