# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='slug')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='配图')),
                ('content', models.TextField(verbose_name='内容')),
                ('position', models.CharField(choices=[('sidepanel', 'sidepanel'), ('home', 'home')], max_length=36, verbose_name='位置')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='栏目名称')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='简要说明')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细说明')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='缩略图')),
                ('official_website', models.URLField(blank=True, null=True, verbose_name='跳转地址')),
                ('m_type', models.CharField(choices=[('blog', 'blog'), ('picture', 'picture'), ('theme', 'theme')], max_length=36, verbose_name='栏目类别')),
            ],
            options={
                'verbose_name': '网站栏目',
                'verbose_name_plural': '网站栏目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CATEGORY'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
