# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('en', '中英译'), ('ja', '中日译')], max_length=36, verbose_name='翻译类别')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='配图')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='原文标题')),
                ('origin_content', models.TextField(verbose_name='原文')),
                ('tran_title', models.CharField(max_length=255, unique=True, verbose_name='译文标题')),
                ('tran_content', models.TextField(verbose_name='译文')),
                ('o_t_content', models.TextField(verbose_name='参照')),
                ('position', models.CharField(choices=[('sidepanel', 'sidepanel'), ('home', 'home')], max_length=36, verbose_name='位置')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '翻译',
                'verbose_name_plural': '翻译',
                'ordering': ['-createtime'],
            },
        ),
    ]
